### ISSUE TITLE
New version of subword-nmt can't handle certain sentences

### ISSUE THREAD

**Issue by edunov** [rsennrich/subword-nmt#41]
There are several sentences in WMT dataset that used to work fine, but currently break, I was able to narrow down the problem

1) Double space and special caracters:
```
echo "and &#93;  . &apos;" | python $BPEROOT/learn_bpe.py -s 10
#version: 0.2
Traceback (most recent call last):
  File "subword-nmt/learn_bpe.py", line 254, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "subword-nmt/learn_bpe.py", line 199, in main
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
  File "subword-nmt/learn_bpe.py", line 199, in <listcomp>
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
IndexError: string index out of range

```

2) Empty string:

```
$ echo "hello world
> " | python $BPEROOT/learn_bpe.py -s 10
#version: 0.2
Traceback (most recent call last):
  File "subword-nmt/learn_bpe.py", line 254, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "subword-nmt/learn_bpe.py", line 199, in main
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
  File "subword-nmt/learn_bpe.py", line 199, in <listcomp>
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
IndexError: string index out of range
```

Both of those worked with older versions of subword-nmt, e.g. with this one: 8247488

**Comment by rsennrich** [comment]
thanks; fixed in aa1bd. Another unwanted side effect of commits 30e5be and 0541c3.
